### PR TITLE
Refactor/remove launcher

### PR DESCRIPTION
**Pull request by JulianFeinauer**
refactor: remove launcher pseudo-app

Removes launcher pseudo app and solely relies on omap.py to start the platform

### CODE REVIEW

**Review by NiklasMerz — APPROVED** [review]

**Comment by NiklasMerz** [comment]
@JulianFeinauer I rebased it to fix the conflict. Now the CI is broken. You probably know what to do.

**Comment by JulianFeinauer** [comment]
@NiklasMerz the issue is indeed a valid one.
Its pytest_django crashing because I removed the settings.py file.
So to be able to use pytest django with the "omap" construction we need a slightly patched version of pytest_django, I guess...

**Comment by JulianFeinauer** [comment]
@NiklasMerz I opened an issue on pytest-django, that would solve the problem for us: https://github.com/pytest-dev/pytest-django/issues/1001

**Comment by JulianFeinauer** [comment]
@NiklasMerz you see a demo implementaton here: https://github.com/pytest-dev/pytest-django/pull/1002
And this is how the code would need to be modified to work, if the PR above would be merged: https://github.com/pragmaticindustries/open-machine-plattform/tree/feature/new-launcher-with-pytest-fixes

**Comment by JulianFeinauer** [comment]
@NiklasMerz thanks to your hint its green again now : )

**Review by NiklasMerz — APPROVED** [review]

**Pull request merged**
